services:
  timescaledb:
    image: timescale/timescaledb-ha:pg16
    container_name: timescaledb
    environment:
      - POSTGRES_DB=electricity_invoices
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    networks:
      - electricity-invoices-network
    volumes:
      - electricity-invoices-dbdata:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  electricity-invoices-network:
    driver: bridge

volumes:
  electricity-invoices-dbdata:
    driver: local
