"""add_hourly_block_levels

Revision ID: e2dc09a8d572
Revises: fa105b85ec97
Create Date: 2025-09-08 21:16:20.962213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2dc09a8d572'
down_revision: Union[str, Sequence[str], None] = 'fa105b85ec97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_hourly_block_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('day_type', sa.Enum('WORKDAY', 'OFFDAY', name='hourly_block_levels_day_type'), nullable=False),
    sa.Column('electricity_season_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('hour >= 0 AND hour <= 23', name='hourly_block_levels_hours_valid'),
    sa.CheckConstraint('level >= 1 AND level <= 5', name='hourly_block_levels_valid'),
    sa.ForeignKeyConstraint(['electricity_season_id'], ['config_electricity_seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('config_hourly_block_levels')
    # ### end Alembic commands ###
