"""create_electricity_seasons_config

Revision ID: fa105b85ec97
Revises: 3bb0acdd7998
Create Date: 2025-09-08 20:38:18.629663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa105b85ec97'
down_revision: Union[str, Sequence[str], None] = '3bb0acdd7998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_electricity_seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_key', sa.String(), nullable=False),
    sa.Column('season_name', sa.String(), nullable=False),
    sa.Column('start_month', sa.Integer(), nullable=False),
    sa.Column('end_month', sa.Integer(), nullable=False),
    sa.Column('crosses_calendar_year', sa.Boolean(), sa.Computed('start_month > end_month', persisted=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('start_month >= 1 AND start_month <= 12 AND end_month >= 1 AND end_month <= 12', name='electricity_seasons_month_values'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('config_electricity_seasons')
    # ### end Alembic commands ###
