"""insert_supplier_data

Revision ID: a81066a32763
Revises: d6708c592cb1
Create Date: 2025-09-08 23:52:00.718236

"""
from datetime import datetime
from io import StringIO
import os
from typing import Sequence, Union

from alembic import op
import pandas as pd
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision: str = 'a81066a32763'
down_revision: Union[str, Sequence[str], None] = 'd6708c592cb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # create from csv by COPY 

    path = os.getcwd() + '/alembic/data/supplier_info.csv'
    df = pd.read_csv(path, sep=";")
    df['created_at'] = datetime.now()
    df['updated_at'] = df['created_at']
    data = df.to_dict(orient='records')

    conn = op.get_bind()
    for row in data:        
        conn.execute(
            text("""INSERT INTO electricity_providers (full_title, email, webpage, tax_code, iban_number, street_address, zip_code, zip_name, created_at, updated_at)
                    VALUES (:full_title, :email, :webpage, :tax_code, :iban_number, :street_address, :zip_code, :zip_name, :created_at, :updated_at)"""),
            row
        )


    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM electricity_providers")
    # ### end Alembic commands ###
