"""add_mesurements_electricity_usage

Revision ID: d6708c592cb1
Revises: e2dc09a8d572
Create Date: 2025-09-08 23:49:18.482896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6708c592cb1'
down_revision: Union[str, Sequence[str], None] = 'e2dc09a8d572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurements_electricity_usage',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumption_kwh', sa.Float(), nullable=False),
    sa.Column('price_per_kwh', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['electricity_customers.id'], ),
    sa.PrimaryKeyConstraint('customer_id', 'measured_at')
    )
    # ### end Alembic commands ###

    # create hypertable for efficient timeseries usage
    op.execute("SELECT create_hypertable('measurements_electricity_usage', 'measured_at')")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measurements_electricity_usage')
    # ### end Alembic commands ###
