"""add_customers_and_supplier

Revision ID: 3bb0acdd7998
Revises: abf0be0b2e47
Create Date: 2025-09-08 20:37:24.273454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bb0acdd7998'
down_revision: Union[str, Sequence[str], None] = 'abf0be0b2e47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('electricity_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(), nullable=False),
    sa.Column('issued_date', sa.DateTime(), nullable=False),
    sa.Column('service_date', sa.DateTime(), nullable=False),
    sa.Column('location_issued', sa.String(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('invoice_code', sa.String(), nullable=False),
    sa.Column('payment_reason', sa.String(), nullable=False),
    sa.Column('receiver_IBAN', sa.String(), nullable=False),
    sa.Column('receiver_reference', sa.String(), nullable=False),
    sa.Column('base_amount', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['electricity_customers_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('electricity_invoices_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('electricity_invoice_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date_from', sa.DateTime(), nullable=False),
    sa.Column('date_to', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['electricity_invoice_id'], ['electricity_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('electricity_invoices_items')
    op.drop_table('electricity_invoices')
    # ### end Alembic commands ###
