"""add_mesurements_electricity_usage

Revision ID: 83172ebf2d6c
Revises: e2dc09a8d572
Create Date: 2025-09-08 23:44:39.168716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83172ebf2d6c'
down_revision: Union[str, Sequence[str], None] = 'e2dc09a8d572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurements_electricity_usage',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumption_kwh', sa.Float(), nullable=False),
    sa.Column('price_per_kwh', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['electricity_customers.id'], ),
    sa.PrimaryKeyConstraint('customer_id', 'measured_at')
    )
    op.create_index('ix_customer_electricity_measurements', 'measurements_electricity_usage', ['customer_id', sa.literal_column('measured_at DESC')], unique=False)
    # ### end Alembic commands ###

    # create hypertable for timeseries manualy
    op.execute("SELECT create_hypertable('measurements_electricity_usage', 'measured_at')")

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customer_electricity_measurements', table_name='measurements_electricity_usage')
    op.drop_table('measurements_electricity_usage')
    # ### end Alembic commands ###
