"""added_invoice_field_total_quantity

Revision ID: bb8e4e337e8f
Revises: 4585778264d6
Create Date: 2025-09-10 20:59:51.344359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb8e4e337e8f'
down_revision: Union[str, Sequence[str], None] = '4585778264d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('electricity_invoices', sa.Column('total_quantity', sa.Float(), nullable=False))
    op.drop_index(op.f('measurements_electricity_usage_measured_at_idx'), table_name='measurements_electricity_usage')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('measurements_electricity_usage_measured_at_idx'), 'measurements_electricity_usage', [sa.literal_column('measured_at DESC')], unique=False)
    op.drop_column('electricity_invoices', 'total_quantity')
    # ### end Alembic commands ###
