"""insert_electricity_seasons_config

Revision ID: dc6f1d82e9d2
Revises: a81066a32763
Create Date: 2025-09-09 15:13:58.544397

"""
from datetime import datetime
import os
import pandas as pd
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision: str = 'dc6f1d82e9d2'
down_revision: Union[str, Sequence[str], None] = 'a81066a32763'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    path = os.getcwd() + '/alembic/data/seasons_range.csv'
    df = pd.read_csv(path, sep=";")
    df['created_at'] = datetime.now()
    df['updated_at'] = df['created_at']
    data = df.to_dict(orient='records')

    conn = op.get_bind()
    for row in data:        
        conn.execute(
            text("""INSERT INTO config_electricity_seasons (season_key, season_name, start_month, end_month, created_at, updated_at)
                    VALUES (:season_key, :season_name, :start_month, :end_month, :created_at, :updated_at)"""),
            row
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM config_electricity_seasons")
    # ### end Alembic commands ###
