"""add_customers_suppliers

Revision ID: 3dbfa2496102
Revises: 
Create Date: 2025-09-08 18:42:02.676911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dbfa2496102'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('electricity_customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('tax_code', sa.String(), nullable=False),
    sa.Column('street_address', sa.String(), nullable=False),
    sa.Column('zip_code', sa.Integer(), nullable=False),
    sa.Column('zip_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('electricity_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_title', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('webpage', sa.String(), nullable=False),
    sa.Column('tax_code', sa.String(), nullable=False),
    sa.Column('iban_number', sa.String(), nullable=False),
    sa.Column('street_address', sa.String(), nullable=False),
    sa.Column('zip_code', sa.Integer(), nullable=False),
    sa.Column('zip_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('electricity_customer_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('customer_type', sa.Enum('RESIDENTIAL', 'BUSINESS', 'MUNICIPIAL', name='electricity_customer_contract_type'), nullable=False),
    sa.Column('contract_number', sa.String(), nullable=False),
    sa.Column('energy_meter_number', sa.String(), nullable=False),
    sa.Column('package_name', sa.String(), nullable=False),
    sa.Column('termination_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['electricity_customers.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['electricity_providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('electricity_customer_contracts')
    op.drop_table('electricity_providers')
    op.drop_table('electricity_customers')
    # ### end Alembic commands ###
